// <auto-generated />
using AspNet06Store.ShopUI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNet06Store.ShopUI.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240923205047_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNet06Store.ShopUI.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 2,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 3,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 4,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 5,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 6,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 7,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 8,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 9,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        },
                        new
                        {
                            ID = 10,
                            Category = "",
                            Description = "",
                            Name = "",
                            Price = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
