// <auto-generated />
using AspNet06Store.ShopUI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNet06Store.ShopUI.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240927181853_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNet06Store.ShopUI.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Iphone",
                            Description = "",
                            Name = "Apple 16",
                            Price = 100
                        },
                        new
                        {
                            ID = 2,
                            Category = "Samsung",
                            Description = "",
                            Name = "A70",
                            Price = 6000
                        },
                        new
                        {
                            ID = 3,
                            Category = "Iphone",
                            Description = "",
                            Name = "Iphone 12",
                            Price = 47000
                        },
                        new
                        {
                            ID = 4,
                            Category = "Iphone",
                            Description = "",
                            Name = "Iphone13",
                            Price = 0
                        },
                        new
                        {
                            ID = 5,
                            Category = "Samsung",
                            Description = "",
                            Name = "Samsung A20",
                            Price = 43000
                        },
                        new
                        {
                            ID = 6,
                            Category = "Samsung",
                            Description = "",
                            Name = "Samsung A18",
                            Price = 56000
                        },
                        new
                        {
                            ID = 7,
                            Category = "Iphone",
                            Description = "",
                            Name = "Iphone11",
                            Price = 340000
                        },
                        new
                        {
                            ID = 8,
                            Category = "Nokia",
                            Description = "",
                            Name = "Nokia SS2",
                            Price = 34000
                        },
                        new
                        {
                            ID = 9,
                            Category = "Iphone",
                            Description = "",
                            Name = "Iphone14",
                            Price = 50000
                        },
                        new
                        {
                            ID = 10,
                            Category = "Nokia",
                            Description = "",
                            Name = "Nokia500",
                            Price = 30000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
